# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DS345SettingsSweep_UI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DS345Settings(object):
    def setupUi(self, DS345Settings):
        DS345Settings.setObjectName("DS345Settings")
        DS345Settings.resize(400, 221)
        DS345Settings.setMinimumSize(QtCore.QSize(253, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(DS345Settings)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupOutput = QtWidgets.QGroupBox(DS345Settings)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupOutput.setFont(font)
        self.groupOutput.setObjectName("groupOutput")
        self.gridLayout = QtWidgets.QGridLayout(self.groupOutput)
        self.gridLayout.setContentsMargins(4, 2, 4, 2)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.ModWaveform = QtWidgets.QComboBox(self.groupOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ModWaveform.sizePolicy().hasHeightForWidth())
        self.ModWaveform.setSizePolicy(sizePolicy)
        self.ModWaveform.setObjectName("ModWaveform")
        self.ModWaveform.addItem("")
        self.ModWaveform.addItem("")
        self.ModWaveform.addItem("")
        self.ModWaveform.addItem("")
        self.ModWaveform.addItem("")
        self.ModWaveform.addItem("")
        self.ModWaveform.addItem("")
        self.gridLayout.addWidget(self.ModWaveform, 6, 4, 1, 1)
        self.labelModWaveform = QtWidgets.QLabel(self.groupOutput)
        self.labelModWaveform.setObjectName("labelModWaveform")
        self.gridLayout.addWidget(self.labelModWaveform, 6, 1, 1, 1)
        self.SweepRate = QtWidgets.QDoubleSpinBox(self.groupOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SweepRate.sizePolicy().hasHeightForWidth())
        self.SweepRate.setSizePolicy(sizePolicy)
        self.SweepRate.setDecimals(0)
        self.SweepRate.setMinimum(1.0)
        self.SweepRate.setMaximum(1000000.0)
        self.SweepRate.setSingleStep(1.0)
        self.SweepRate.setProperty("value", 1.0)
        self.SweepRate.setObjectName("SweepRate")
        self.gridLayout.addWidget(self.SweepRate, 3, 4, 1, 1)
        self.Stopfrequency = QtWidgets.QDoubleSpinBox(self.groupOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Stopfrequency.sizePolicy().hasHeightForWidth())
        self.Stopfrequency.setSizePolicy(sizePolicy)
        self.Stopfrequency.setDecimals(6)
        self.Stopfrequency.setMinimum(1e-05)
        self.Stopfrequency.setMaximum(100000.0)
        self.Stopfrequency.setProperty("value", 1.0)
        self.Stopfrequency.setObjectName("Stopfrequency")
        self.gridLayout.addWidget(self.Stopfrequency, 2, 4, 1, 1)
        self.labelSweepRate = QtWidgets.QLabel(self.groupOutput)
        self.labelSweepRate.setObjectName("labelSweepRate")
        self.gridLayout.addWidget(self.labelSweepRate, 3, 1, 1, 1)
        self.ModType = QtWidgets.QComboBox(self.groupOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ModType.sizePolicy().hasHeightForWidth())
        self.ModType.setSizePolicy(sizePolicy)
        self.ModType.setObjectName("ModType")
        self.ModType.addItem("")
        self.ModType.addItem("")
        self.ModType.addItem("")
        self.ModType.addItem("")
        self.ModType.addItem("")
        self.ModType.addItem("")
        self.gridLayout.addWidget(self.ModType, 5, 4, 1, 1)
        self.labelStopFrequency = QtWidgets.QLabel(self.groupOutput)
        self.labelStopFrequency.setObjectName("labelStopFrequency")
        self.gridLayout.addWidget(self.labelStopFrequency, 2, 1, 1, 1)
        self.labelModType = QtWidgets.QLabel(self.groupOutput)
        self.labelModType.setObjectName("labelModType")
        self.gridLayout.addWidget(self.labelModType, 5, 1, 1, 1)
        self.labelStartFrequency = QtWidgets.QLabel(self.groupOutput)
        self.labelStartFrequency.setObjectName("labelStartFrequency")
        self.gridLayout.addWidget(self.labelStartFrequency, 0, 1, 1, 1)
        self.Startfrequency = QtWidgets.QDoubleSpinBox(self.groupOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Startfrequency.sizePolicy().hasHeightForWidth())
        self.Startfrequency.setSizePolicy(sizePolicy)
        self.Startfrequency.setDecimals(6)
        self.Startfrequency.setMinimum(1e-05)
        self.Startfrequency.setMaximum(100000.0)
        self.Startfrequency.setProperty("value", 1.0)
        self.Startfrequency.setObjectName("Startfrequency")
        self.gridLayout.addWidget(self.Startfrequency, 0, 4, 1, 1)
        self.modOnOff = QtWidgets.QComboBox(self.groupOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modOnOff.sizePolicy().hasHeightForWidth())
        self.modOnOff.setSizePolicy(sizePolicy)
        self.modOnOff.setObjectName("modOnOff")
        self.modOnOff.addItem("")
        self.modOnOff.addItem("")
        self.gridLayout.addWidget(self.modOnOff, 7, 4, 1, 1)
        self.labelModSetter = QtWidgets.QLabel(self.groupOutput)
        self.labelModSetter.setObjectName("labelModSetter")
        self.gridLayout.addWidget(self.labelModSetter, 7, 1, 1, 1)
        self.stop = QtWidgets.QPushButton(self.groupOutput)
        self.stop.setObjectName("stop")
        self.gridLayout.addWidget(self.stop, 8, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupOutput)
        self.labelModWaveform.setBuddy(self.ModWaveform)
        self.labelSweepRate.setBuddy(self.SweepRate)

        self.retranslateUi(DS345Settings)
        self.ModType.setCurrentIndex(0)
        self.stop.clicked.connect(DS345Settings.close)
        QtCore.QMetaObject.connectSlotsByName(DS345Settings)

    def retranslateUi(self, DS345Settings):
        _translate = QtCore.QCoreApplication.translate
        DS345Settings.setWindowTitle(_translate("DS345Settings", "DS345"))
        DS345Settings.setStatusTip(_translate("DS345Settings", "DS345: Controls"))
        self.groupOutput.setTitle(_translate("DS345Settings", "Sweep Output Configuration"))
        self.ModWaveform.setStatusTip(_translate("DS345Settings", "DS345: Mod Waveform"))
        self.ModWaveform.setItemText(0, _translate("DS345Settings", "single sweep"))
        self.ModWaveform.setItemText(1, _translate("DS345Settings", "ramp"))
        self.ModWaveform.setItemText(2, _translate("DS345Settings", "triangle"))
        self.ModWaveform.setItemText(3, _translate("DS345Settings", "sine"))
        self.ModWaveform.setItemText(4, _translate("DS345Settings", "square"))
        self.ModWaveform.setItemText(5, _translate("DS345Settings", "arbitrary"))
        self.ModWaveform.setItemText(6, _translate("DS345Settings", "none"))
        self.labelModWaveform.setText(_translate("DS345Settings", "Modulation Waveform"))
        self.SweepRate.setStatusTip(_translate("DS345Settings", "DS345: Mod Rate"))
        self.SweepRate.setSuffix(_translate("DS345Settings", " Hz/s"))
        self.Stopfrequency.setStatusTip(_translate("DS345Settings", "DS345: Stop Frequency [Hz]"))
        self.Stopfrequency.setSuffix(_translate("DS345Settings", " Hz"))
        self.labelSweepRate.setText(_translate("DS345Settings", "Sweep Rate"))
        self.ModType.setStatusTip(_translate("DS345Settings", "DS345: Mod Type"))
        self.ModType.setItemText(0, _translate("DS345Settings", "linear "))
        self.ModType.setItemText(1, _translate("DS345Settings", "log"))
        self.ModType.setItemText(2, _translate("DS345Settings", "AM"))
        self.ModType.setItemText(3, _translate("DS345Settings", "FM"))
        self.ModType.setItemText(4, _translate("DS345Settings", "PM"))
        self.ModType.setItemText(5, _translate("DS345Settings", "burst"))
        self.labelStopFrequency.setText(_translate("DS345Settings", "Stop Frequency"))
        self.labelModType.setText(_translate("DS345Settings", "Modulation Type"))
        self.labelStartFrequency.setText(_translate("DS345Settings", "Start Frequency"))
        self.Startfrequency.setStatusTip(_translate("DS345Settings", "DS345: Start Frequency [Hz]"))
        self.Startfrequency.setSuffix(_translate("DS345Settings", " Hz"))
        self.modOnOff.setStatusTip(_translate("DS345Settings", "DS345: ModOnOff"))
        self.modOnOff.setItemText(0, _translate("DS345Settings", "Off"))
        self.modOnOff.setItemText(1, _translate("DS345Settings", "On"))
        self.labelModSetter.setText(_translate("DS345Settings", "Modulation Setter"))
        self.stop.setText(_translate("DS345Settings", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DS345Settings = QtWidgets.QWidget()
    ui = Ui_DS345Settings()
    ui.setupUi(DS345Settings)
    DS345Settings.show()
    sys.exit(app.exec_())

