# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DS345SettingsSweep_UI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DS345Settings(object):
    def setupUi(self, DS345Settings):
        DS345Settings.setObjectName("DS345Settings")
        DS345Settings.resize(400, 446)
        DS345Settings.setMinimumSize(QtCore.QSize(253, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(DS345Settings)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupOutput = QtWidgets.QGroupBox(DS345Settings)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupOutput.setFont(font)
        self.groupOutput.setObjectName("groupOutput")
        self.gridLayout = QtWidgets.QGridLayout(self.groupOutput)
        self.gridLayout.setContentsMargins(4, 2, 4, 2)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.labelOffset = QtWidgets.QLabel(self.groupOutput)
        self.labelOffset.setObjectName("labelOffset")
        self.gridLayout.addWidget(self.labelOffset, 4, 1, 1, 1)
        self.labelModType = QtWidgets.QLabel(self.groupOutput)
        self.labelModType.setObjectName("labelModType")
        self.gridLayout.addWidget(self.labelModType, 6, 1, 1, 1)
        self.labelSweepRate = QtWidgets.QLabel(self.groupOutput)
        self.labelSweepRate.setObjectName("labelSweepRate")
        self.gridLayout.addWidget(self.labelSweepRate, 3, 1, 1, 1)
        self.modrate = QtWidgets.QDoubleSpinBox(self.groupOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modrate.sizePolicy().hasHeightForWidth())
        self.modrate.setSizePolicy(sizePolicy)
        self.modrate.setDecimals(0)
        self.modrate.setMinimum(1.0)
        self.modrate.setMaximum(1000000.0)
        self.modrate.setSingleStep(1.0)
        self.modrate.setProperty("value", 1.0)
        self.modrate.setObjectName("modrate")
        self.gridLayout.addWidget(self.modrate, 3, 4, 1, 1)
        self.labelStopFrequency = QtWidgets.QLabel(self.groupOutput)
        self.labelStopFrequency.setObjectName("labelStopFrequency")
        self.gridLayout.addWidget(self.labelStopFrequency, 2, 1, 1, 1)
        self.labelModWaveform = QtWidgets.QLabel(self.groupOutput)
        self.labelModWaveform.setObjectName("labelModWaveform")
        self.gridLayout.addWidget(self.labelModWaveform, 7, 1, 1, 1)
        self.modtype = QtWidgets.QComboBox(self.groupOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modtype.sizePolicy().hasHeightForWidth())
        self.modtype.setSizePolicy(sizePolicy)
        self.modtype.setObjectName("modtype")
        self.modtype.addItem("")
        self.modtype.addItem("")
        self.modtype.addItem("")
        self.modtype.addItem("")
        self.modtype.addItem("")
        self.modtype.addItem("")
        self.gridLayout.addWidget(self.modtype, 6, 4, 1, 1)
        self.modOnOff = QtWidgets.QComboBox(self.groupOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modOnOff.sizePolicy().hasHeightForWidth())
        self.modOnOff.setSizePolicy(sizePolicy)
        self.modOnOff.setObjectName("modOnOff")
        self.modOnOff.addItem("")
        self.modOnOff.addItem("")
        self.gridLayout.addWidget(self.modOnOff, 8, 4, 1, 1)
        self.stopfrequency = QtWidgets.QDoubleSpinBox(self.groupOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopfrequency.sizePolicy().hasHeightForWidth())
        self.stopfrequency.setSizePolicy(sizePolicy)
        self.stopfrequency.setDecimals(6)
        self.stopfrequency.setMinimum(1e-05)
        self.stopfrequency.setMaximum(1000000.0)
        self.stopfrequency.setProperty("value", 1.0)
        self.stopfrequency.setObjectName("stopfrequency")
        self.gridLayout.addWidget(self.stopfrequency, 2, 4, 1, 1)
        self.labelStartFrequency = QtWidgets.QLabel(self.groupOutput)
        self.labelStartFrequency.setObjectName("labelStartFrequency")
        self.gridLayout.addWidget(self.labelStartFrequency, 0, 1, 1, 1)
        self.modwaveform = QtWidgets.QComboBox(self.groupOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modwaveform.sizePolicy().hasHeightForWidth())
        self.modwaveform.setSizePolicy(sizePolicy)
        self.modwaveform.setObjectName("modwaveform")
        self.modwaveform.addItem("")
        self.modwaveform.addItem("")
        self.modwaveform.addItem("")
        self.modwaveform.addItem("")
        self.modwaveform.addItem("")
        self.modwaveform.addItem("")
        self.modwaveform.addItem("")
        self.gridLayout.addWidget(self.modwaveform, 7, 4, 1, 1)
        self.startfrequency = QtWidgets.QDoubleSpinBox(self.groupOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startfrequency.sizePolicy().hasHeightForWidth())
        self.startfrequency.setSizePolicy(sizePolicy)
        self.startfrequency.setDecimals(6)
        self.startfrequency.setMinimum(1e-05)
        self.startfrequency.setMaximum(1000000.0)
        self.startfrequency.setProperty("value", 1.0)
        self.startfrequency.setObjectName("startfrequency")
        self.gridLayout.addWidget(self.startfrequency, 0, 4, 1, 1)
        self.labelModSetter = QtWidgets.QLabel(self.groupOutput)
        self.labelModSetter.setObjectName("labelModSetter")
        self.gridLayout.addWidget(self.labelModSetter, 8, 1, 1, 1)
        self.offset = QtWidgets.QDoubleSpinBox(self.groupOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offset.sizePolicy().hasHeightForWidth())
        self.offset.setSizePolicy(sizePolicy)
        self.offset.setMinimum(-5.0)
        self.offset.setMaximum(5.0)
        self.offset.setSingleStep(0.1)
        self.offset.setObjectName("offset")
        self.gridLayout.addWidget(self.offset, 4, 4, 1, 1)
        self.labelAmplitude = QtWidgets.QLabel(self.groupOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAmplitude.sizePolicy().hasHeightForWidth())
        self.labelAmplitude.setSizePolicy(sizePolicy)
        self.labelAmplitude.setObjectName("labelAmplitude")
        self.gridLayout.addWidget(self.labelAmplitude, 5, 1, 1, 1)
        self.amplitude = QtWidgets.QDoubleSpinBox(self.groupOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amplitude.sizePolicy().hasHeightForWidth())
        self.amplitude.setSizePolicy(sizePolicy)
        self.amplitude.setMaximum(5.0)
        self.amplitude.setSingleStep(0.1)
        self.amplitude.setProperty("value", 1.0)
        self.amplitude.setObjectName("amplitude")
        self.gridLayout.addWidget(self.amplitude, 5, 4, 1, 1)
        self.verticalLayout.addWidget(self.groupOutput)
        self.labelOffset.setBuddy(self.offset)
        self.labelSweepRate.setBuddy(self.modrate)
        self.labelModWaveform.setBuddy(self.modwaveform)

        self.retranslateUi(DS345Settings)
        self.modtype.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DS345Settings)

    def retranslateUi(self, DS345Settings):
        _translate = QtCore.QCoreApplication.translate
        DS345Settings.setWindowTitle(_translate("DS345Settings", "DS345"))
        DS345Settings.setStatusTip(_translate("DS345Settings", "DS345: Controls"))
        self.groupOutput.setTitle(_translate("DS345Settings", "Sweep Output Configuration"))
        self.labelOffset.setText(_translate("DS345Settings", "Offset"))
        self.labelModType.setText(_translate("DS345Settings", "Modulation Type"))
        self.labelSweepRate.setText(_translate("DS345Settings", "Sweep Rate"))
        self.modrate.setStatusTip(_translate("DS345Settings", "DS345: Mod Rate"))
        self.modrate.setSuffix(_translate("DS345Settings", " Hz"))
        self.labelStopFrequency.setText(_translate("DS345Settings", "Stop Frequency"))
        self.labelModWaveform.setText(_translate("DS345Settings", "Modulation Waveform"))
        self.modtype.setStatusTip(_translate("DS345Settings", "DS345: Mod Type"))
        self.modtype.setItemText(0, _translate("DS345Settings", "linear "))
        self.modtype.setItemText(1, _translate("DS345Settings", "log"))
        self.modtype.setItemText(2, _translate("DS345Settings", "AM"))
        self.modtype.setItemText(3, _translate("DS345Settings", "FM"))
        self.modtype.setItemText(4, _translate("DS345Settings", "PM"))
        self.modtype.setItemText(5, _translate("DS345Settings", "burst"))
        self.modOnOff.setStatusTip(_translate("DS345Settings", "DS345: ModOnOff"))
        self.modOnOff.setItemText(0, _translate("DS345Settings", "Off"))
        self.modOnOff.setItemText(1, _translate("DS345Settings", "On"))
        self.stopfrequency.setStatusTip(_translate("DS345Settings", "DS345: Stop Frequency [Hz]"))
        self.stopfrequency.setSuffix(_translate("DS345Settings", " Hz"))
        self.labelStartFrequency.setText(_translate("DS345Settings", "Start Frequency"))
        self.modwaveform.setStatusTip(_translate("DS345Settings", "DS345: Mod Waveform"))
        self.modwaveform.setItemText(0, _translate("DS345Settings", "single sweep"))
        self.modwaveform.setItemText(1, _translate("DS345Settings", "ramp"))
        self.modwaveform.setItemText(2, _translate("DS345Settings", "triangle"))
        self.modwaveform.setItemText(3, _translate("DS345Settings", "sine"))
        self.modwaveform.setItemText(4, _translate("DS345Settings", "square"))
        self.modwaveform.setItemText(5, _translate("DS345Settings", "arbitrary"))
        self.modwaveform.setItemText(6, _translate("DS345Settings", "none"))
        self.startfrequency.setStatusTip(_translate("DS345Settings", "DS345: Start Frequency [Hz]"))
        self.startfrequency.setSuffix(_translate("DS345Settings", " Hz"))
        self.labelModSetter.setText(_translate("DS345Settings", "Modulation Setter"))
        self.offset.setStatusTip(_translate("DS345Settings", "DS345: Offset"))
        self.offset.setSuffix(_translate("DS345Settings", " V"))
        self.labelAmplitude.setText(_translate("DS345Settings", "Amplitude"))
        self.amplitude.setStatusTip(_translate("DS345Settings", "DS345: Amplitude"))
        self.amplitude.setSuffix(_translate("DS345Settings", " Vpp"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DS345Settings = QtWidgets.QWidget()
    ui = Ui_DS345Settings()
    ui.setupUi(DS345Settings)
    DS345Settings.show()
    sys.exit(app.exec_())

