# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DS345SettingsSweep_UI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DS345SettingsSweep(object):
    def setupUi(self, DS345SettingsSweep):
        DS345SettingsSweep.setObjectName("DS345SettingsSweep")
        DS345SettingsSweep.resize(404, 365)
        DS345SettingsSweep.setMinimumSize(QtCore.QSize(253, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(DS345SettingsSweep)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupOutput = QtWidgets.QGroupBox(DS345SettingsSweep)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupOutput.setFont(font)
        self.groupOutput.setObjectName("groupOutput")
        self.gridLayout = QtWidgets.QGridLayout(self.groupOutput)
        self.gridLayout.setContentsMargins(4, 2, 4, 2)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.labelModType = QtWidgets.QLabel(self.groupOutput)
        self.labelModType.setObjectName("labelModType")
        self.gridLayout.addWidget(self.labelModType, 6, 0, 1, 1)
        self.SweepRate = QtWidgets.QDoubleSpinBox(self.groupOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SweepRate.sizePolicy().hasHeightForWidth())
        self.SweepRate.setSizePolicy(sizePolicy)
        self.SweepRate.setDecimals(0)
        self.SweepRate.setMinimum(1.0)
        self.SweepRate.setMaximum(1000000.0)
        self.SweepRate.setSingleStep(1.0)
        self.SweepRate.setProperty("value", 1.0)
        self.SweepRate.setObjectName("SweepRate")
        self.gridLayout.addWidget(self.SweepRate, 4, 1, 1, 1)
        self.labelModWaveform = QtWidgets.QLabel(self.groupOutput)
        self.labelModWaveform.setObjectName("labelModWaveform")
        self.gridLayout.addWidget(self.labelModWaveform, 7, 0, 1, 1)
        self.ModWaveform = QtWidgets.QComboBox(self.groupOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ModWaveform.sizePolicy().hasHeightForWidth())
        self.ModWaveform.setSizePolicy(sizePolicy)
        self.ModWaveform.setObjectName("ModWaveform")
        self.ModWaveform.addItem("")
        self.ModWaveform.addItem("")
        self.ModWaveform.addItem("")
        self.ModWaveform.addItem("")
        self.ModWaveform.addItem("")
        self.ModWaveform.addItem("")
        self.ModWaveform.addItem("")
        self.gridLayout.addWidget(self.ModWaveform, 7, 1, 1, 1)
        self.Startfrequency = QtWidgets.QDoubleSpinBox(self.groupOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Startfrequency.sizePolicy().hasHeightForWidth())
        self.Startfrequency.setSizePolicy(sizePolicy)
        self.Startfrequency.setDecimals(6)
        self.Startfrequency.setMinimum(1e-05)
        self.Startfrequency.setMaximum(100000.0)
        self.Startfrequency.setProperty("value", 1.0)
        self.Startfrequency.setObjectName("Startfrequency")
        self.gridLayout.addWidget(self.Startfrequency, 0, 1, 1, 1)
        self.labelSweepRate = QtWidgets.QLabel(self.groupOutput)
        self.labelSweepRate.setObjectName("labelSweepRate")
        self.gridLayout.addWidget(self.labelSweepRate, 4, 0, 1, 1)
        self.labelStartFrequency = QtWidgets.QLabel(self.groupOutput)
        self.labelStartFrequency.setObjectName("labelStartFrequency")
        self.gridLayout.addWidget(self.labelStartFrequency, 0, 0, 1, 1)
        self.labelStopFrequency = QtWidgets.QLabel(self.groupOutput)
        self.labelStopFrequency.setObjectName("labelStopFrequency")
        self.gridLayout.addWidget(self.labelStopFrequency, 3, 0, 1, 1)
        self.Stopfrequency = QtWidgets.QDoubleSpinBox(self.groupOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Stopfrequency.sizePolicy().hasHeightForWidth())
        self.Stopfrequency.setSizePolicy(sizePolicy)
        self.Stopfrequency.setDecimals(6)
        self.Stopfrequency.setMinimum(1e-05)
        self.Stopfrequency.setMaximum(100000.0)
        self.Stopfrequency.setProperty("value", 1.0)
        self.Stopfrequency.setObjectName("Stopfrequency")
        self.gridLayout.addWidget(self.Stopfrequency, 3, 1, 1, 1)
        self.ModType = QtWidgets.QComboBox(self.groupOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ModType.sizePolicy().hasHeightForWidth())
        self.ModType.setSizePolicy(sizePolicy)
        self.ModType.setObjectName("ModType")
        self.ModType.addItem("")
        self.ModType.addItem("")
        self.ModType.addItem("")
        self.ModType.addItem("")
        self.ModType.addItem("")
        self.ModType.addItem("")
        self.gridLayout.addWidget(self.ModType, 6, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupOutput)
        self.labelModWaveform.setBuddy(self.ModWaveform)
        self.labelSweepRate.setBuddy(self.SweepRate)

        self.retranslateUi(DS345SettingsSweep)
        self.ModType.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DS345SettingsSweep)

    def retranslateUi(self, DS345SettingsSweep):
        _translate = QtCore.QCoreApplication.translate
        DS345SettingsSweep.setWindowTitle(_translate("DS345SettingsSweep", "DS345"))
        DS345SettingsSweep.setStatusTip(_translate("DS345SettingsSweep", "DS345: Controls"))
        self.groupOutput.setTitle(_translate("DS345SettingsSweep", "Sweep Output Configuration"))
        self.labelModType.setText(_translate("DS345SettingsSweep", "Modulation Type"))
        self.SweepRate.setStatusTip(_translate("DS345SettingsSweep", "DS345: Mod Rate"))
        self.SweepRate.setSuffix(_translate("DS345SettingsSweep", " Hz/s"))
        self.labelModWaveform.setText(_translate("DS345SettingsSweep", "Modulation Waveform"))
        self.ModWaveform.setStatusTip(_translate("DS345SettingsSweep", "DS345: Waveform"))
        self.ModWaveform.setItemText(0, _translate("DS345SettingsSweep", "single sweep"))
        self.ModWaveform.setItemText(1, _translate("DS345SettingsSweep", "ramp"))
        self.ModWaveform.setItemText(2, _translate("DS345SettingsSweep", "triangle"))
        self.ModWaveform.setItemText(3, _translate("DS345SettingsSweep", "sine"))
        self.ModWaveform.setItemText(4, _translate("DS345SettingsSweep", "square"))
        self.ModWaveform.setItemText(5, _translate("DS345SettingsSweep", "arbitrary"))
        self.ModWaveform.setItemText(6, _translate("DS345SettingsSweep", "none"))
        self.Startfrequency.setStatusTip(_translate("DS345SettingsSweep", "DS345: Start Frequency [Hz]"))
        self.Startfrequency.setSuffix(_translate("DS345SettingsSweep", " Hz"))
        self.labelSweepRate.setText(_translate("DS345SettingsSweep", "Sweep Rate"))
        self.labelStartFrequency.setText(_translate("DS345SettingsSweep", "Start Frequency"))
        self.labelStopFrequency.setText(_translate("DS345SettingsSweep", "Stop Frequency"))
        self.Stopfrequency.setStatusTip(_translate("DS345SettingsSweep", "DS345: Stop Frequency [Hz]"))
        self.Stopfrequency.setSuffix(_translate("DS345SettingsSweep", " Hz"))
        self.ModType.setStatusTip(_translate("DS345SettingsSweep", "DS345: Mod Type"))
        self.ModType.setItemText(0, _translate("DS345SettingsSweep", "linear "))
        self.ModType.setItemText(1, _translate("DS345SettingsSweep", "log"))
        self.ModType.setItemText(2, _translate("DS345SettingsSweep", "AM"))
        self.ModType.setItemText(3, _translate("DS345SettingsSweep", "FM"))
        self.ModType.setItemText(4, _translate("DS345SettingsSweep", "PM"))
        self.ModType.setItemText(5, _translate("DS345SettingsSweep", "burst"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DS345SettingsSweep = QtWidgets.QWidget()
    ui = Ui_DS345SettingsSweep()
    ui.setupUi(DS345SettingsSweep)
    DS345SettingsSweep.show()
    sys.exit(app.exec_())
